version: '{build}'

image:
- Visual Studio 2017

configuration: Release

before_build:
- cmd: dotnet --info
- cmd: dotnet restore --verbosity m

after_build:
- cmd: dotnet pack src\AppMetricsSerilogReporter

artifacts:
- path: src\**\*.nupkg