version: 0.1.{build}

os: Visual Studio 2017

skip_tags: true

clone_depth: 1

configuration: Release

before_build:
- cmd: dotnet --version
- cmd: dotnet restore --verbosity m

after_build:
- cmd: dotnet pack src\AppMetricsSerilogReporter

artifacts:
- path: src\**\*.nupkg
  name: MyGet